language: php

php:
  - 5.5

before_script:
  - composer install
  - phpenv rehash

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover
  - php vendor/bin/phpcs -n --standard=PSR2 --ignore=vendor .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
