site_name: Particle Filter
theme: readthedocs
pages:
- [index.md, Home]
- [installation.md, Installing]
- [basic-usage.md, Basic usage]
- [filter-rules.md, Filter-rules]
- [extending.md, Extending the Filter]
- [multibyte-encoding.md, Multibyte encoding]
